package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"errors"
	"strconv"
	"strings"

	"github.com/AlekSi/pointer"
	"github.com/GigaDesk/eardrum-server/auth"
	"github.com/GigaDesk/eardrum-server/graph/model"
	"github.com/GigaDesk/eardrum-server/shutdown"
	"github.com/rs/zerolog/log"
)

// CreateJob is the resolver for the CreateJob field.
func (r *mutationResolver) CreateJob(ctx context.Context, input model.NewJob) (*model.JobProfile, error) {
	//check if system is in shutdown mode
	if *shutdown.IsShutdown {
		return nil, errors.New("System is shut down for maintainance. We are sorry for any incoveniences caused")
	}
	user, err := auth.ForContext(ctx)
	if err != nil {
		return nil, err
	}
	if user == nil {
		return nil, errors.New("access to create job denied!")
	}
	role := user.GetRole()
	if role != "admin" {
		return nil, errors.New("access to create job denied. Only available for registered and logged in admins. To fix check access token!")
	}

	id, err := user.GetID()

	if err != nil {
		errors.New("could not access admin's id!")
	}

	log.Info().Str("role", role).Int("id", id).Str("path", "AddStudents").Msg("adding students")

	//Join input.Requiremets with "||" separator

	requirements := strings.Join(input.Requirements, "||")

	n := &model.Job{
		Title:          input.Title,
		Industry:       input.Industry,
		Description:    input.Description,
		Level:          input.Level,
		Location:       input.Location,
		Deadline:       input.Deadline,
		EducationLevel: input.EducationLevel,
		MinSalary:      input.MinSalary,
		MaxSalary:      input.MaxSalary,
		Experience:     input.Experience,
		Requirements:   &requirements,
	}

	//Create records in postgres
	if err := r.Sql.Db.Create(n).Error; err != nil {
		log.Error().Str("Job Title", n.Title).Str("path", "CreateJob").Msg(err.Error())
		return nil, errors.New("an unexpected error occurred while creating the job. please try again later or contact support")
	}

	jobprofile := &model.JobProfile{
		ID:             n.ID,
		CreatedAt:      n.CreatedAt,
		UpdatedAt:      n.UpdatedAt,
		DeletedAt:      n.DeletedAt,
		Title:          n.Title,
		Industry:       n.Industry,
		Description:    n.Description,
		Level:          n.Level,
		Location:       n.Location,
		Deadline:       n.Deadline,
		EducationLevel: n.EducationLevel,
		MinSalary:      n.MinSalary,
		MaxSalary:      n.MaxSalary,
		Experience:     n.Experience,
		Requirements:   strings.Split(pointer.GetString(n.Requirements), "||"),
	}

	return jobprofile, nil
}

// CreateUnapprovedJob is the resolver for the createUnapprovedJob field.
func (r *mutationResolver) CreateUnapprovedJob(ctx context.Context, input model.NewJob) (*model.JobProfile, error) {
	//check if system is in shutdown mode
	if *shutdown.IsShutdown {
		return nil, errors.New("System is shut down for maintainance. We are sorry for any incoveniences caused")
	}

	//Join input.Requiremets with "||" separator

	requirements := strings.Join(input.Requirements, "||")

	n := &model.UnapprovedJob{
		Title:          input.Title,
		Industry:       input.Industry,
		Description:    input.Description,
		Level:          input.Level,
		Location:       input.Location,
		Deadline:       input.Deadline,
		EducationLevel: input.EducationLevel,
		MinSalary:      input.MinSalary,
		MaxSalary:      input.MaxSalary,
		Experience:     input.Experience,
		Requirements:   &requirements,
	}

	//Create records in postgres
	if err := r.Sql.Db.Create(n).Error; err != nil {
		log.Error().Str("Job Title", n.Title).Str("path", "CreateUnapprovedJob").Msg(err.Error())
		return nil, errors.New("an unexpected error occurred while creating the unapproved job. please try again later or contact support")
	}

	jobprofile := &model.JobProfile{
		ID:             n.ID,
		CreatedAt:      n.CreatedAt,
		UpdatedAt:      n.UpdatedAt,
		DeletedAt:      n.DeletedAt,
		Title:          n.Title,
		Industry:       n.Industry,
		Description:    n.Description,
		Level:          n.Level,
		Location:       n.Location,
		Deadline:       n.Deadline,
		EducationLevel: n.EducationLevel,
		MinSalary:      n.MinSalary,
		MaxSalary:      n.MaxSalary,
		Experience:     n.Experience,
		Requirements:   strings.Split(pointer.GetString(n.Requirements), "||"),
	}

	return jobprofile, nil
}

// ApproveJob is the resolver for the approveJob field.
func (r *mutationResolver) ApproveJob(ctx context.Context, id int) (*model.JobProfile, error) {
	//declare an unapprovedjob variable
	var unapprovedjob *model.UnapprovedJob

	// Find the first unapproved job that matches the input id from the unapproved job table
	if err := r.Sql.Db.Where("id = ?", id).First(&unapprovedjob).Error; err != nil {
		log.Info().Int("id", id).Str("path", "ApproveJob").Msg("id does not exist")
		return nil, errors.New("error finding unappproved job with id: " + strconv.Itoa(id))
	}

	// transform the unapproved job model into job model and copy it
	job := &model.Job{
		Title:          unapprovedjob.Title,
		Industry:       unapprovedjob.Industry,
		Description:    unapprovedjob.Description,
		Level:          unapprovedjob.Level,
		Location:       unapprovedjob.Location,
		Deadline:       unapprovedjob.Deadline,
		EducationLevel: unapprovedjob.EducationLevel,
		MinSalary:      unapprovedjob.MinSalary,
		MaxSalary:      unapprovedjob.MaxSalary,
		Experience:     unapprovedjob.Experience,
		Requirements:   unapprovedjob.Requirements,
	}

	// take the newly transformed and copied job data and transfer it into the official verified job table
	if err := r.Sql.Db.Create(job).Error; err != nil {
		log.Info().Str("Title", job.Title).Str("path", "ApproveJob").Msg(err.Error())
		return nil, errors.New("Failed to approve job. please try again later or contact support")
	}

	// delete the unapproved job from the unapproved job table
	if err := r.Sql.Db.Delete(unapprovedjob).Error; err != nil {
		log.Error().Str("path", "ApprovedJob").Int("record_id", unapprovedjob.ID).Msg(err.Error())
		return nil, errors.New("Failed to complete job approval. please try again later or contact support")
	}

	log.Info().Int("initial_record_id", unapprovedjob.ID).Int("final_record_id", unapprovedjob.ID).Str("path", "ApproveJob").Msg("completed unapproved job to job data transaction")

	jobprofile := &model.JobProfile{
		ID:             job.ID,
		CreatedAt:      job.CreatedAt,
		UpdatedAt:      job.UpdatedAt,
		DeletedAt:      job.DeletedAt,
		Title:          job.Title,
		Industry:       job.Industry,
		Description:    job.Description,
		Level:          job.Level,
		Location:       job.Location,
		Deadline:       job.Deadline,
		EducationLevel: job.EducationLevel,
		MinSalary:      job.MinSalary,
		MaxSalary:      job.MaxSalary,
		Experience:     job.Experience,
		Requirements:   strings.Split(pointer.GetString(job.Requirements), "||"),
	}

	return jobprofile, nil
}

// GetJobs is the resolver for the getJobs field.
func (r *queryResolver) GetJobs(ctx context.Context) ([]*model.JobProfile, error) {
	//check if system is in shutdown mode
	if *shutdown.IsShutdown {
		return nil, errors.New("System is shut down for maintainance. We are sorry for any incoveniences caused")
	}

	var jobs []*model.Job
	if err := r.Sql.Db.Find(&jobs).Error; err != nil {
		log.Error().Str("path", "GetJobs").Msg(err.Error())
		return nil, errors.New("could not access jobs!")
	}
	log.Info().Str("path", "GetJobs").Msg("getting jobs")

	var jobprofiles []*model.JobProfile

	for _, job := range jobs {
		jobprofile := &model.JobProfile{
			ID:             job.ID,
			CreatedAt:      job.CreatedAt,
			UpdatedAt:      job.UpdatedAt,
			DeletedAt:      job.DeletedAt,
			Title:          job.Title,
			Industry:       job.Industry,
			Description:    job.Description,
			Level:          job.Level,
			Location:       job.Location,
			Deadline:       job.Deadline,
			EducationLevel: job.EducationLevel,
			MinSalary:      job.MinSalary,
			MaxSalary:      job.MaxSalary,
			Experience:     job.Experience,
			Requirements:   strings.Split(pointer.GetString(job.Requirements), "||"),
		}
		jobprofiles = append(jobprofiles, jobprofile)
	}

	return jobprofiles, nil
}

// GetUnapprovedJobs is the resolver for the getUnapprovedJobs field.
func (r *queryResolver) GetUnapprovedJobs(ctx context.Context) ([]*model.JobProfile, error) {
	//check if system is in shutdown mode
	if *shutdown.IsShutdown {
		return nil, errors.New("System is shut down for maintainance. We are sorry for any incoveniences caused")
	}

	var jobs []*model.UnapprovedJob
	if err := r.Sql.Db.Find(&jobs).Error; err != nil {
		log.Error().Str("path", "GetUnapprovedJobs").Msg(err.Error())
		return nil, errors.New("could not access unapproved jobs!")
	}
	log.Info().Str("path", "GetUnapprovedJobs").Msg("getting unapproved jobs")

	var jobprofiles []*model.JobProfile

	for _, job := range jobs {
		jobprofile := &model.JobProfile{
			ID:             job.ID,
			CreatedAt:      job.CreatedAt,
			UpdatedAt:      job.UpdatedAt,
			DeletedAt:      job.DeletedAt,
			Title:          job.Title,
			Industry:       job.Industry,
			Description:    job.Description,
			Level:          job.Level,
			Location:       job.Location,
			Deadline:       job.Deadline,
			EducationLevel: job.EducationLevel,
			MinSalary:      job.MinSalary,
			MaxSalary:      job.MaxSalary,
			Experience:     job.Experience,
			Requirements:   strings.Split(pointer.GetString(job.Requirements), "||"),
		}
		jobprofiles = append(jobprofiles, jobprofile)
	}

	return jobprofiles, nil
}
